name: release-deploy

on:
  release:
    types: [ published ]

jobs:

  deploy-windows-exe:
    strategy:
      fail-fast: true
      matrix:
        python-version: [ '3.10' ]

    runs-on: 'windows-latest'
    name: Deploy Windows executable with Python ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Build package
      run: |
        python -m pip install --upgrade pip
        python -m pip install build
        python -m build

    - name: Build Windows executables
      run: |
        python -m pip install -r requirements-dev.txt
        pyinstaller dicom-validator.spec -y

    - name: Publish Windows executables on GitHub
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: dist/*.exe

  publish-to-pypi:
    strategy:
      fail-fast: true
      matrix:
        python-version: [ '3.10' ]


    runs-on: 'ubuntu-latest'
    name: Deploy to PyPi with Python ${{ matrix.python-version }}
    needs: deploy-windows-exe

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Build package
      run: |
        python -m pip install --upgrade pip
        python -m pip install build
        python -m build

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_TOKEN_VALIDATOR }}
